### ISSUE TITLE
auto incubate new eggs

### ISSUE THREAD

**Issue by sidg2681** [shiftcodeYT/PokeBot4#105]
so far everything is working perfectly i shifted my account to new york central park and now i have a xp rate of 57000 per hr
if only i didnt have to log in through my phone to incubate eggs
if i log in through my phone the bot even notices my displacement and walks to it which is good but now i am over 100k miles away so
is it possible to autoincubate new eggs
ps : reached level 38 on my main so just need to do the last stretch otherwise bot works perfectly also i think this is the best bot on the internet so far and i tried both c++ and python bots so far so see if u can publish it or something for donations

**Comment by shiftcodeYT** [comment]
I'll look into it soon.

**Comment by AzureACW** [comment]
@sidg2681 Turn off location on your phone before logging in to the app, you can look at your pokedex, manage pokemon and eggs and such without updating your account location. This would be an awesome feature though. :)

**Comment by shiftcodeYT** [comment]
cleanup: added
