### ISSUE TITLE
"Don't catch" list?

### ISSUE THREAD

**Issue by topkekz** [shiftcodeYT/PokeBot4#140]
It used to be in the older version of PokeBot 3 but that feature was removed in the latest version (before the API stuff), would it be possible to bring it back in the new version?

**Comment by shiftcodeYT** [comment]
@topkekz Well, the unwanted list immediately transfers it if caught, which gets you experience. I don't see why you would want to get the old list back. Convince me and i'll add it :)

**Comment by topkekz** [comment]
This may sound stupid but I wouldn't like to gain XP/level up too fast. Since there are way too many Pidgeys and Weedles around the XP gain is crazy fast for me. But oh well, at least only utilizing the nocatch.txt without adding anything to the GUI would be nice.

**Comment by shiftcodeYT** [comment]
It's back :D
