### ISSUE TITLE
Error reloading pokemon list ?

### ISSUE THREAD

**Issue by conmcgu** [shiftcodeYT/PokeBot4#145]
Title says it all bot works just keeps saying this all the time though

**Comment by conmcgu** [comment]
Says out of memory after the error

**Comment by cokelight** [comment]
same

**Comment by shiftcodeYT** [comment]
@cokelight try deleting the "Sprites" folder

**Comment by cokelight** [comment]
dont have that folder

**Comment by shiftcodeYT** [comment]
@cokelight ._.

**Comment by cokelight** [comment]
![cattura1](https://cloud.githubusercontent.com/assets/20746305/17526906/8b2fe91a-5e69-11e6-9a07-0449c05737bb.PNG)

**Comment by shiftcodeYT** [comment]
@cokelight well thats the problem then. run as admin maybe it creates that folder thne

**Comment by cokelight** [comment]
ok ill try :+1:

**Comment by cokelight** [comment]
![cattura3](https://cloud.githubusercontent.com/assets/20746305/17527552/19737ece-5e6c-11e6-845d-271cd325ee89.PNG)
unable to reload pokemon's list

**Comment by shiftcodeYT** [comment]
@cokelight you havent got enough RAM.

**Comment by shiftcodeYT** [comment]
It's normal if you dont have enough ram that it doesnt work. I'll put a notice in.
