### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by C3rberus9** [shiftcodeYT/PokeBot4#146]
I have a i5 4200H in my laptop, and the bot uses approx. 30% of it... I consider this as a bit more, than normal, 'cause it's just a bot, it should use much less of CPU.

Dunno if it is supposed, to work so, or this is some issue, I reported it, just to be sure.

**Comment by shiftcodeYT** [comment]
@C3rberus9 i also noticed that myself. It appears to be the CPU, i may put in delays later today

**Comment by C3rberus9** [comment]
Thanks :)

**Comment by shiftcodeYT** [comment]
@C3rberus9 i think i know the problem, in the check that updates the GUI, is a while(true)/infinite loop. I forgot delays :P

**Comment by C3rberus9** [comment]
Yeah i though of something like this too, jus wasn't sure about it so i better don't say anything :D 
btw, nice if u think u have the problem and can solve it too.

**Comment by FallenDev** [comment]
I want to first off say, awesome job Simon! I'm at work so I can't test the new improves you've made. However, from what I'm seeing you did an amazing job. I'd run a debug within visual and check the performance logs and see if there is any memory leaks as well. Might be something simple like the infinite loop you've mentioned.

**Comment by shiftcodeYT** [comment]
@FallenDev im almost sure its the infinite :D

**Comment by shiftcodeYT** [comment]
@FallenDev can you chech for memory leaks in Console/Pokemons.cs?

**Comment by shiftcodeYT** [comment]
Also, i uploaded a new version with fixed CPU usage :)

**Comment by tiny1980** [comment]
My issue with last version was when the pokelist loads up.
Everything stays greyed out, and continually says Reloading.... in it's status bar.

Is this the same issue you just worked on?  either way I will try this release out and see.

**Comment by shiftcodeYT** [comment]
@tiny1980 First load takes over 5 minutes, that's normal

**Comment by tiny1980** [comment]
@shiftcodeYT thanks, I'll be patient then!   lol..  in the previous instances (pre-API change) it loaded fairly quickly.

**Comment by shiftcodeYT** [comment]
@tiny1980 i know, dunno why its so slow

**Comment by shiftcodeYT** [comment]
Fixed in latest release
