### ISSUE TITLE
can't find any pokestop again

### ISSUE THREAD

**Issue by cokelight** [shiftcodeYT/PokeBot4#147]
i have this issues again
![cattura0](https://cloud.githubusercontent.com/assets/20746305/17525085/8ec82b4e-5e61-11e6-816c-3e26744bfa0b.PNG)

**Comment by shiftcodeYT** [comment]
@cokelight try other coordinates

**Comment by cokelight** [comment]
i tried but nothis changes...same error

**Comment by shiftcodeYT** [comment]
@cokelight well, it works for everybody else. try redownloading newest release and extracting it into a different folder

**Comment by cokelight** [comment]
ok now seems work.

**Comment by shiftcodeYT** [comment]
@cokelight servers unstable.

**Comment by cokelight** [comment]
no i was using 4 bots together and sometimes it gave me this error ...soft ban 1336..i dont know why...with two no problems..

**Comment by shiftcodeYT** [comment]
@cokelight well everything after 3 instances will get you softbanned
